# Generated by Django 5.0.2 on 2025-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfLivingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('rent', models.FloatField(help_text='Average rent for 1 bedroom apartment')),
                ('groceries', models.FloatField(help_text='Monthly groceries cost')),
                ('utilities', models.FloatField(help_text='Monthly utilities cost')),
                ('transportation', models.FloatField(help_text='Monthly transportation cost')),
                ('income', models.FloatField(help_text='Average monthly income')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cost of Living Data',
            },
        ),
    ]
